CREATE CONSTRAINT pessoa_id IF NOT EXISTS
FOR (p:Pessoa)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT empresa_id IF NOT EXISTS
FOR (e:Empresa)
REQUIRE e.id IS UNIQUE;

CREATE CONSTRAINT habilidade_id IF NOT EXISTS
FOR (h:Habilidade)
REQUIRE h.id IS UNIQUE;